### ISSUE TITLE
About the simulation environment

### ISSUE THREAD

**Issue by lucky-dzy** [roboterax/humanoid-gym#11]
The Isaac Gym Preview 4 version used in the project is older and has many known problems, such as contact force, coordinate system, model solution, etc.

I noticed that legged_gym has been ported to the new simulation platform orbit in January this year. Will the author consider porting in the future?

**Comment by wangyenjen** [comment]
Hi @lucky-dzy ,

We are planning to migrate our codebase from Isaac Gym to another physical simulation platform. If you are interested in this initiative, please feel free to contact us. There could be an opportunity for collaboration. : )
