### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by pauradime** [roboterax/humanoid-gym#14]
Hello, I am really interested in this project and would like to have implement it. 

During installation setup, you mentioned using python 3.8 in the first step, however, in step 3 it does not seem to be compatible with it, here is the output: 

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.11.* , which can be installed;
└─ torchvision 0.14.1  is not installable because there are no viable options
   ├─ torchvision 0.14.1 would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ torchvision 0.14.1 would require
   │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
   ├─ torchvision 0.14.1 would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   └─ torchvision 0.14.1 would require
      └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported.

It would be greatly appreciated if we could have a further discussion regarding the entire project, please contact me if you are interested, my email address is 1580158828@163.com 
Both Mandarin and English are fine with me. 

Thank you in advance 

All the best
Zhengting Li

**Comment by wangyenjen** [comment]
Hi @pauradime,

It's difficult to assess the issue you're facing. Could you provide more details, such as the installation command you used and the Python packages you have installed?

Additionally, you might want to try replacing step 3 with the following command:
``` bash
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
```

Best,
Yen-Jen
