### ISSUE TITLE
Domain rand

### ISSUE THREAD

**Issue by ChengEeee** [roboterax/humanoid-gym#2]
I see that the code has many domain randomization Settings, as shown in the figure, but only a small part of them are used. Can such Settings ensure the robustness of sim2real
![image](https://github.com/roboterax/humanoid-gym/assets/94172651/af522aad-f262-43ed-93b9-75967d1f3f4a)
![image](https://github.com/roboterax/humanoid-gym/assets/94172651/8059cdc6-4321-4a82-a298-1fede761857f)

**Comment by zlw21gxy** [comment]
We have identified and resolved some unused settings in the file. Additionally, we are excited to introduce a new DR term called 'Dynamic Randomization.' Before transferring your policy to the real world, we recommend using the 'sim2sim' tool. We have also enhanced the sim2im feature. You are welcome to try these enhancements and provide your feedback.
