### ISSUE TITLE
load new URDF

### ISSUE THREAD

**Issue by gaoboyi** [roboterax/humanoid-gym#22]
when i change the urdf path， i found there have some .STL file. How can i get the .STL file of my own urdf file.
![Uploading 截图 2024-07-04 14-56-20.png…]()

**Comment by gaoboyi** [comment]
![截图 2024-07-04 14-56-20](https://github.com/roboterax/humanoid-gym/assets/174687222/197b5a76-fdb6-4778-b1f9-2848533acaf9)

**Comment by Riccardo-Romio** [comment]
how did you solve this?
