### ISSUE TITLE
XBot sim2sim can't walk

### ISSUE THREAD

**Issue by 1725917163** [roboterax/humanoid-gym#24]
Dear author: 
       Thank you very much for your work. I trained your robot in Isaac Gym and it can walk normally, but when I verified it with mujoco, I found that it can't walk normally. Is there any important modification I overlooked? I didn't make any changes to your code during this process. I look forward to your reply.

**Comment by zlw21gxy** [comment]
We have conducted multiple tests and the issue did not occur. Could you furnish more particulars? Kindly attempt our default policy initially. We offer one trained policy as a baseline. In the event of any system setup disparities, ensure that the baseline policy functions properly. Subsequently, verify whether you continue to encounter the identical problem.

**Comment by 1725917163** [comment]
Hi, the default strategy works fine, but the model after training still doesn't work properly (simtosim.py), I didn't modify any code before training started.

https://github.com/user-attachments/assets/de8555fd-9d4f-4880-aaac-7542dd887334

**Comment by zlw21gxy** [comment]
Do you just pull the project without making any modifications? How many iterations have you gone through in training? Please offer some training logs, like the last few training iterations. That would be helpful.

**Comment by 1725917163** [comment]
You are right, I found that iterating a few more times solved the problem. Thank you very much for your reply

**Comment by zlw21gxy** [comment]
I will close it as it has been solved. One comment is that more training steps do not guarantee a better sim2real result. After the reward function converges, training for a few hundred more steps is a common practice, and training for at least 1,000 steps is a good starting point.
