### ISSUE TITLE
您好，请问如果我想在isaacgym那个渲染的界面（运行python scripts/play.py --task=humanoid_ppo --run_name v1代码时出现的界面）出现多个机器人，而不只是一个机器人，我应该怎么做呢，谢谢！

### ISSUE THREAD

**Issue by xiaoyuyinb666** [roboterax/humanoid-gym#39]

**Comment by zlw21gxy** [comment]
add argument `--num_envs 1`

**Comment by xiaoyuyinb666** [comment]
谢谢佬！

**Comment by zlw21gxy** [comment]
In https://github.com/roboterax/humanoid-gym/blob/620c5fac0cebbad60a36caa35b5ff30a0c78e4e2/humanoid/scripts/play.py#L51, we set the maximum number to 1. You can change it to a larger number and add the argument `--num_envs 32`, for example. This will allow you to render 32 robots at the same time.
