### ISSUE TITLE
Model migration questions

### ISSUE THREAD

**Issue by zhangqingbo6** [roboterax/humanoid-gym#4]
Hello author! Your open source code can very well solve the walking problem of our humanoid robot. But after several days of trying, we have a problem that we haven't solved yet.
Our model can walk normally when training "plane", but it cannot walk normally when training "trimesh", and even forgets how to walk. We increased the number of iterations to 10,000 before the robot could barely walk. I would like to ask which part of the modification have we overlooked? Or what should I pay attention to when changing models?

**Comment by zlw21gxy** [comment]
For optimal performance, kindly switch to our most recent main branch where we've addressed a bug issue, which should now function properly.

**Comment by zhangqingbo6** [comment]
After downloading the new project, I'm glad that issue has been resolved. But we have a question: Why does the input env.commands fluctuate and the robot cannot keep walking in a straight line during play. We have not made any modifications to the orange lines as follows:
![image](https://github.com/roboterax/humanoid-gym/assets/56789308/5ffcd4c3-f150-4608-a170-08dd9b189db9)

**Comment by wangyenjen** [comment]
Hi @zhangqingbo6 ,

The input fluctuations occur because the system is programmed to randomly resample the command every 8 seconds, after which it switches to the default command specified in the play script. To ignore this behavior, you can modify the `_resample_commands` function within the environment.
