### ISSUE TITLE
地形

### ISSUE THREAD

**Issue by gytrtjyk** [roboterax/humanoid-gym#44]
你好。我想启用地形的三角形网格，并且取消注释以下行play.py：env_cfg.terrain.mesh_type = 'trimesh'。然后调用python3 humanoid/scripts/play.py --task=humanoid_ppo --run_name v1 --num_envs 2 --terrain；显示play.py: error: unrecognized arguments: --terrain这是为什么

**Comment by zlw21gxy** [comment]
There is no argument called `--terrain`. If you want to train or play with terrain, you can enable it in the training configuration. Change the `mesh_type` to `trimesh`.
https://github.com/roboterax/humanoid-gym/blob/ae46e201c85a2b17e7f2cea59a441dae7ea88a8f/humanoid/envs/custom/humanoid_config.py#L73

**Comment by gytrtjyk** [comment]
谢谢您，但是我已经取消掉注释了，并且把平面的注释掉，但为什么显示还是平面地形
