### ISSUE TITLE
Is the ankle kp = 15 a typo or a feature?

### ISSUE THREAD

**Issue by cyoahs** [roboterax/humanoid-gym#5]
Hello!

In the [config file](https://github.com/roboterax/humanoid-gym/blob/c28486e6a7ef90e6da6d5f1e5eb455179bc74a52/humanoid/envs/custom/humanoid_config.py#L120) I found that kp = 15 and kd = 10 for the ankles. The kp/kd pair seems mismatching compared to other joints. Is it a typo for kp = 150 or an intentional design?

**Comment by wangyenjen** [comment]
Hi @cyoahs ,

The difference in magnitude of ankle PD can be seen in the URDF of many humanoid robots. : )
