### ISSUE TITLE
Hard Coded Value in legged_robot.py

### ISSUE THREAD

**Issue by Ke-Wang1017** [roboterax/humanoid-gym#7]
Hi just realized that in the init_buffers() function the dimension of self.rigid_states is hard-coded, this might cause problems if other robots are used and has different number of bodies

https://github.com/roboterax/humanoid-gym/blob/main/humanoid/envs/base/legged_robot.py#L455

**Comment by wangyenjen** [comment]
Hi @Ke-Wang1017 ,

Polish up:

Thanks for drawing our attention to this problem! In this [PR](https://github.com/roboterax/humanoid-gym/pull/10), @jufrick has helped us to address it. Much appreciated, you guys!
